controller:
   plural: true
   paths: 
   - /app/controllers/

model:
   paths: 
   - /app/models/

view:
   plural: true
   dir: true
   paths: 
   - /app/views/

helper:
   plural: true
   paths: 
   - /app/helpers/

mailer:
   paths: 
   - /app/mailers/

migration:
   plural: true
   paths: 
   - /db/migrate/

unit:   
   paths: 
   - /test/unit/
   - /test/unit/helpers/

functional:
   plural: true
   paths:
   - /test/functional/

integration:
   paths:
   - /test/integration/

performance:
   paths:
   - /test/performance/

fixture:
   plural: true
   paths:
   - /test/fixtures/

route:
   plural: true
   paths:
   - /config/routes.rb
   extract: true
