controller:
   plural: true
   suffix: _controller.rb
   paths: 
   - /app/controllers/

model:
   suffix: .rb
   paths: 
   - /app/models/

view:
   plural: true
   dir: true
   paths: 
   - /app/views/

helper:
   plural: true
   suffix: _helper.rb
   paths: 
   - /app/helpers/

mailer:
   paths: 
   - /app/mailers/

migration:
   plural: true
   update_filename: true
   extract: true
   dir: true
   paths: 
   - /db/migrate/

unit:   
   suffix: "*_test.rb"
   paths: 
   - /test/unit/
   - /test/unit/helpers/

functional:
   plural: true
   suffix: _controller_test.rb
   paths:
   - /test/functional/

integration:
   paths:
   - /test/integration/

performance:
   paths:
   - /test/performance/

fixture:
   plural: true
   suffix: .yml
   paths:
   - /test/fixtures/

route:
   plural: true
   paths:
   - /config/routes.rb
   extract: true
